name: simple_dart_list_renderer
description: List Renderer
version: 0.0.1
repository: https://github.com/simple-dart/list_renderer
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.6

